#!/usr/bin/env bash

python worker.py $HOSTNAME
python worker.py $HOSTNAME
python worker.py $HOSTNAME
python worker.py $HOSTNAME
python worker.py $HOSTNAME
python worker.py $HOSTNAME
python worker.py $HOSTNAME
python worker.py $HOSTNAME
python worker.py $HOSTNAME
python worker.py $HOSTNAME
python worker.py $HOSTNAME
python worker.py $HOSTNAME
python worker.py $HOSTNAME
python worker.py $HOSTNAME
python worker.py $HOSTNAME
python worker.py $HOSTNAME
python worker.py $HOSTNAME
python worker.py $HOSTNAME
python worker.py $HOSTNAME
python worker.py $HOSTNAME
python worker.py $HOSTNAME
python worker.py $HOSTNAME
python worker.py $HOSTNAME
python worker.py $HOSTNAME
python worker.py $HOSTNAME
python worker.py $HOSTNAME
python worker.py $HOSTNAME
python worker.py $HOSTNAME
python worker.py $HOSTNAME
python worker.py $HOSTNAME
python worker.py $HOSTNAME
python worker.py $HOSTNAME
python worker.py $HOSTNAME
python worker.py $HOSTNAME